---
title: "About the Data"
execute:
  echo: false
  include: false
editor_options: 
  chunk_output_type: console
---


```{r}
# workspace
library(leaflet)
library(leafem)
library(leaflet.extras)

setwd("C:/Users/lotte.pohl/Documents/github_repos/OpenSeaLabHackathon_SmoothSharks")
source(paste0(getwd(), "/01_code/overview_map.R"))

```


## Shark detection data

## Study Area

```{r map}
#|include: true

map_overview <- 
  leaflet(options = leafletOptions(zoomControl = T,
                                                         minZoom = 7, maxZoom = 15,
                                                         dragging = T)) %>%
  addTiles(group = "OpenStreetMap") %>%
  addProviderTiles("Esri.WorldImagery", options = providerTileOptions(opacity = 0.6), group = "satellite") %>%
  # leaflet() %>%
  setView(4.2, 51.48, zoom = 7.5) %>%
  addScaleBar(position = "bottomleft", options = scaleBarOptions(maxWidth = 250, imperial = F)) %>%
  
  addTiles() %>% 
  leafem::addMouseCoordinates() %>%
  addRasterImage(bathy_belgium_raster, opacity = 1, colors = "viridis", group = "bathymetry") %>%
  addCircleMarkers(data = receiver_stations_info,
                   lat = ~deploy_latitude,
                   lng = ~deploy_longitude,
                   radius = 3,
                   fillOpacity = 1,
                   opacity = 1,
                   weight = 0,
                   color = "white",
                   group = "receiver stations points") %>%
  addCircleMarkers(data = receiver_stations_info,
                   lat = ~deploy_latitude,
                   lng = ~deploy_longitude,
                   radius = 3,
                   fillOpacity = 1,
                   opacity = 0,
                   weight = 0,
                   color = "white",
                   group = "receiver station names",
                   label = ~station_name,
                   labelOptions = labelOptions(noHide = T, textOnly = T)) %>%
  # addPolygons(data = eez_netherlands, fillOpacity = 0, opacity = 1, color = "black", weight = 2) %>%
  addPolygons(data = country_belgium, opacity = 1, color = "#ECE4BF", weight = 0.5, fillOpacity = 1, group = "bathymetry") %>%
  addPolygons(data = country_netherlands, opacity = 1, color = "#ECE4BF", weight = 0.5, fillOpacity = 1, group = "bathymetry") %>%
  # addPolygons(data = westernscheldt_boundaries, fillOpacity = 0, opacity = 1, weight = 2, color = "red") %>%
  addPolygons(data = scheldt_boundaries, fillOpacity = 0, opacity = 1, weight = 2, color = "red") %>%
  leafem::addMouseCoordinates() %>%
  addFullscreenControl() %>%
  addLayersControl(position = "topright",
                   baseGroups = c("bathymetry", "satellite", "OpenStreetMap"),
                   overlayGroups = c("receiver station names"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
  addLegend(colors = "red",
            labels = "Schelde Estuary outlines",
            opacity = 1) %>%
  hideGroup("receiver station names")

map_overview
```

