---
title: "About the Project"
---

## Estuaries 

Estuaries are highly complex and dynamic habitats, vital for numerous marine and riverine species who utilize them for feeding, migration, or reproduction grounds. Estuaries must be protected from human interference to protect and maintain their ecological significance. Unfortunately there is a current data scarcity surrounding estuaries as both marine and riverine datasets do not cover them. This increases the difficulty of studying estuarine ecosystems due to the need to merge and combine datasets.
 	
> So how can we truly understand the impact humans have on estuaries? 

For example fishing and dredging, how do they impact the species living in those particular ecosystems?  Perhaps if we understood, for example, the vertical movement of species within the water column, fisheries managers and fishers could be directed with this knowledge to change practice, thereby limiting the number of non-target, endangered and protected species caught as bycatch. 


## The Hackathon 

Using the Open Sea Lab 3.0 Virtual Hackathon 2023 a small group led by Lotte Pohl examined the starry smooth-hound shark presence in the Scheldt Estuary in combination with data from the European Marine Observation and Data network (EMODnet).  

The goal of EMODnet is to make high-quality marine data more accessible by collecting and processing data from a variety of sources. EMODnet has for example bathymetry data which could be used in conjunction with our data sets from the Eastern Scheldt to evaluate our species of interest, the starry smooth-hound shark. 

## The Methods

In order to investigate the behavior of the starry smooth-hound shark, the utilization of acoustic tags was employed to extract comprehensive data from multiple individuals. This methodology was chosen due to its effectiveness in obtaining detailed information regarding the behavioral patterns of the subject. By using acoustic tags, various auditory signals produced by the species can be recorded and monitored, providing insights into its activities, movements, and interactions with the environment. Consequently, the use of acoustic tags as a research tool presents an optimal approach to gather significant data for a comprehensive analysis of the behavioral patterns of the species under study.

### Data Collection

In 2018 and 2019, 30 sharks (19 females and 11 males) were equipped with Acoustic Data Storage Tags (ADST), which comprise an acoustic tag and a data storage tag. Fourteen of the female sharks were detected at receiver stations located in the coastal area at the mouth of the Western Scheldt, a part of the Permanent Belgian Acoustic Receiver Network (PBARN). The presence or absence of the animals from the receiver in a vertical range was determined by the transmission of either a depth or temperature value per detection. One of the 14 detected female sharks had a recovered tag, which allowed access to the complete pressure and temperature log, recording every 120 seconds.

This study represents the beginning of our research efforts to investigate the complexities of species-specific ecological dynamics and the intricate interplay between various environmental factors. Although this work serves as a preliminary case study, our ultimate goal is to broaden the scope of our investigation to include other species and ecosystems, thus enabling a more comprehensive understanding of ecological processes.

## Objectives

The scientific community recognizes that the development of effective conservation strategies depends on the establishment of a comprehensive methodology that can be applied to diverse environmental settings. Our research team seeks to contribute to this collective effort by devising a robust, evidence-based approach that can be implemented across different ecological settings, regardless of the species or ecosystem involved.

To achieve this objective, our team aims to expand on this initial case study by designing and conducting further empirical research endeavors, which will build upon the knowledge base generated from this study. Our focus is to refine and improve our methodology, incorporating feedback from stakeholders and other members of the scientific community to enhance its practical applicability in addressing pressing environmental issues.

We strongly believe that by adopting a comprehensive and inclusive approach to ecological research, we can better understand the intricate dynamics between different ecological factors and identify effective measures to promote sustainable conservation practices. Our research team is committed to contributing to this collective endeavor by generating robust scientific evidence and fostering collaborative research partnerships across different ecological settings.

## About the Team

Lotte Pohl assembled our team called the “Smooth Sharks” for the Hackathon. Members of the team include Wout Decrop, David Casals, Arienne Calonge, and Jennifer Feenstra-Arengård and Silvia Blum.

> For all of us this is our first hackathon. 

* **Lotte** is finishing her master’s degree in Marine Biological Resources and is writing her thesis on the starry smooth-hound shark.

* **Wout** is a bioscience engineer with additional background in coding which helped during this project.

* **David** is an environmental biologist working on the movement ecology of fish in the Mediterranean and Belgian Part of the North Sea using various fish tracking techniques.

* **Arienne** is a marine science researcher and geographer currently focusing on the processing of various acoustic data.

* **Jennifer**, a developmental biologist turned frontend developer, has a strong interest in ocean conservation and helped with the writing of this project. 

* **Silvia** is a barine biology student interested in graphic design.




<!-- # About the Team -->

<!-- Estuaries are highly complex and dynamic habitats, vital for numerous marine and riverine species who utilize them for feeding, migration, or reproduction grounds. Estuaries must be protected from human interference to protect and maintain their ecological significance. Unfortunately there is a current data scarcity surrounding estuaries as both marine and riverine datasets do not cover them. This increases the difficulty of studying estuarine ecosystems due to the need to merge and combine datasets. -->

<!-- > So how can we truly understand the impact humans have on estuaries?  -->

<!-- For example fishing and dredging, how do they impact the species living in those particular ecosystems?  Perhaps if we understood, for example, the vertical movement of species within the water column, fisheries managers and fishers could be directed with this knowledge to change practice, thereby limiting the number of non-target, endangered and protected species caught as bycatch.  -->

<!-- Using the Open Sea Lab 3.0 Virtual Hackathon 2023 a small group led by Lotte Pohl examined the starry smooth-hound shark presence in the Scheldt Estuary in combination with data from the European Marine Observation and Data network (EMODnet).  The goal of EMODnet is to make high-quality marine data more accessible by collecting and processing data from a variety of sources. EMODnet has for example bathymetry data which could be used in conjunction with our data sets from the Eastern Scheldt to evaluate our species of interest, the starry smooth-hound shark.  -->
