---
title: "About the Project"
---

# About the Team

Estuaries are highly complex and dynamic habitats, vital for numerous marine and riverine species who utilize them for feeding, migration, or reproduction grounds. Estuaries must be protected from human interference to protect and maintain their ecological significance. Unfortunately there is a current data scarcity surrounding estuaries as both marine and riverine datasets do not cover them. This increases the difficulty of studying estuarine ecosystems due to the need to merge and combine datasets.
 	
> So how can we truly understand the impact humans have on estuaries? 

For example fishing and dredging, how do they impact the species living in those particular ecosystems?  Perhaps if we understood, for example, the vertical movement of species within the water column, fisheries managers and fishers could be directed with this knowledge to change practice, thereby limiting the number of non-target, endangered and protected species caught as bycatch. 

Using the Open Sea Lab 3.0 Virtual Hackathon 2023 a small group led by Lotte Pohl examined the starry smooth-hound shark presence in the Scheldt Estuary in combination with data from the European Marine Observation and Data network (EMODnet).  The goal of EMODnet is to make high-quality marine data more accessible by collecting and processing data from a variety of sources. EMODnet has for example bathymetry data which could be used in conjunction with our data sets from the Eastern Scheldt to evaluate our species of interest, the starry smooth-hound shark. 
